docs/doc/15-sql-functions/110-semi-structured-functions/flatten.md
docs/doc/15-sql-functions/110-semi-structured-functions/index.md
docs/doc/15-sql-functions/112-table-functions/index.md

docs: flatten

---

docs/doc/14-sql-commands/30-query-operators/json/index.md

added ?, ?|, ?& json operators.

docs: json operators

---

docs/doc/14-sql-commands/40-show/show-databases.md
docs/doc/14-sql-commands/40-show/show-full-columns.md
docs/doc/14-sql-commands/40-show/show-functions.md
docs/doc/14-sql-commands/40-show/show-indexes.md
docs/doc/14-sql-commands/40-show/show-metrics.md
docs/doc/14-sql-commands/40-show/show-processlist.md
docs/doc/14-sql-commands/40-show/show-settings.md
docs/doc/14-sql-commands/40-show/show-table-functions.md

show statements support more filter options

docs: show filters

---

api/cron.js

fix: auto deploy

---

docs/doc/10-deploy/10-node-config/03-environment-variables.md
docs/doc/10-deploy/10-node-config/index.md
docs/doc/14-sql-commands/30-query-operators/json/index.md

added node configurations for cmd-line parameters.

docs: cmd paramters

---

docs/doc/14-sql-commands/00-ddl/105-external-function/index.md

Updated external functions for databend-udf library.

docs: databend-udf library

---

docusaurus.config.js

fix: edit url

---

docs/doc/14-sql-commands/00-ddl/105-external-function/index.md

added a note about enabling external function on Databend Cloud: If you are on Databend Cloud, skip this step and contact us with your allowed IP addresses by creating a ticket on **Support** > **Create New Ticket**.

docs: external function on Databend Cloud

---

docs/doc/14-sql-commands/00-ddl/20-table/index.md

Updated the index page for table-related commands.

docs: table index page

---

docs/doc/15-sql-functions/40-string-functions/index.md
docs/doc/15-sql-functions/40-string-functions/translate.md

Added string function: TRANSLATE

docs: TRANSLATE

---

docs/doc/14-sql-commands/00-ddl/20-table/91-vacuum-drop-table.md

Added LIMIT parameter to VACUUM DROP TABLE.

docs: vacuum drop table limit

---

docs/doc/12-load-data/00-stage/02-stage-files.md
docs/doc/12-load-data/00-transform/05-querying-stage.md
docs/doc/14-sql-commands/00-ddl/10-database/_category_.json
docs/doc/14-sql-commands/00-ddl/100-file-format/_category_.json
docs/doc/14-sql-commands/00-ddl/101-network-policy/_category_.json
docs/doc/14-sql-commands/00-ddl/102-mask-policy/_category_.json
docs/doc/14-sql-commands/00-ddl/103-aggregating-index/_category_.json
docs/doc/14-sql-commands/00-ddl/104-udf/_category_.json
docs/doc/14-sql-commands/00-ddl/105-external-function/_category_.json
docs/doc/14-sql-commands/00-ddl/20-table/_category_.json
docs/doc/14-sql-commands/00-ddl/30-user/_category_.json
docs/doc/14-sql-commands/00-ddl/40-stage/02-ddl-drop-stage.md
docs/doc/14-sql-commands/00-ddl/40-stage/04-ddl-list-stage.md
docs/doc/14-sql-commands/00-ddl/40-stage/05-ddl-remove-stage.md
docs/doc/14-sql-commands/00-ddl/40-stage/06-ddl-show-stages.md
docs/doc/14-sql-commands/00-ddl/40-stage/_category_.json
docs/doc/14-sql-commands/00-ddl/40-stage/presign.md
docs/doc/14-sql-commands/00-ddl/60-view/_category_.json
docs/doc/14-sql-commands/00-ddl/70-clusterkey/_category_.json
docs/doc/14-sql-commands/00-ddl/90-share-endpoint/_category_.json
docs/doc/14-sql-commands/00-ddl/90-share/_category_.json

New order:
1. Catalog
2. Database
3. Table
4. View
5. User & Role
6. Stage (includes PRESIGN)
7. Connection (to be added soon)
8. File Format
9. Cluster Key
10. Aggregating Index
11. User-Defined Function
12. External Function
13. Masking Policy
14. Network Policy
15. Share
16. Share Endpoint

docs: add position to DDL topics

---

docs/doc/10-deploy/09-upgrade/10-compatibility.md

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/
- New Feature

feat: add meta-meta compatibility

---

docs/doc/15-sql-functions/110-semi-structured-functions/flatten.md

added LATERAL keyword to FLATTEN.

docs: lateral flatten

---

docs/doc/12-load-data/01-load/04-http.md

added glob patterns: https://github.com/datafuselabs/databend-docs/issues/62#issuecomment-1817425431

docs: load with glob patterns

---

docs/doc/10-deploy/10-node-config/02-query-config.md
docs/doc/13-monitor/30-tracing.md

Updated tracing-related description.

docs: tracing

---

docs/sql-reference/13-sql-reference/50-file-format-options.md
docs/sql-reference/13-sql-reference/_category_.json

added NULL_FIELD_AS and MISSING_FIELD_AS.

docs: ndjson format options

---

docs/doc/03-develop/01-python.md

added databend-py back in place.

docs: databend-py

---

docs/sql-reference/15-sql-functions/30-datetime-functions/current-timestamp.md
docs/sql-reference/15-sql-functions/30-datetime-functions/index.md

added function CURRENT_TIMESTAMP.

docs: CURRENT_TIMESTAMP

---

docs/sql-reference/15-sql-functions/04-array-functions/index.md

added array functions: array_flatten + array_to_string.

docs: array_flatten + array_to_string

---

docs/sql-reference/13-sql-reference/20-system-tables/system-stream-status.md

added system table `system.stream_status`.

docs: system.stream_status

---

docs/doc/12-visualize/deepnote.md
docs/doc/12-visualize/metabase.md

Merged Metabase & Deepnote from Databend Cloud to Databend

docs: Merge Metabase & Deepnote from Databend Cloud to Databend

---

docs/sql-reference/14-sql-commands/20-query-syntax/01-query-select.md

Added COLUMNS to SELECT statement.

docs: columns keyword

---

.github/workflows/docs.translate.yaml

We need to set up an `OPENAI_API_KEY` for it.
cc @BohuTANG

chore(ci): add a gpt translator

---

docs/cn/sql-reference/14-sql-commands/10-dml/dml-merge.md
docs/sql-reference/14-sql-commands/10-dml/dml-merge.md

- added Output section to MERGE INTO
- Updated the syntax: Source now must have an alias to work.
- Updated the examples.

docs: merge into results

---

docs/cn/developer/01-drivers/01-python.md
docs/developer/01-drivers/01-python.md

https://github.com/datafuselabs/databend-docs/issues/222

docs: fix secure parameter

---

docs/sql-reference/14-sql-commands/00-ddl/stream/index.md

Add Continuous Data Pipeline example

stream: Example: Continuous Data Pipeline

---

docs/sql-reference/14-sql-commands/00-ddl/103-aggregating-index/create-aggregating-index.md
docs/sql-reference/14-sql-commands/00-ddl/103-aggregating-index/drop-aggregating-index.md
docs/sql-reference/14-sql-commands/00-ddl/103-aggregating-index/index.md
docs/sql-reference/14-sql-commands/00-ddl/103-aggregating-index/refresh-aggregating-index.md

- Added SYNC keyword to CREATE AGGREGATING INDEX.
- Added "Refreshing Aggregating Index" section to describe the refresh options.
- Refactored examples for REFRESH AGGREGATING INDEX.

docs: aggregating index updates

---

docs/sql-reference/14-sql-commands/00-ddl/stream/index.md

docs: stream columns

---

docs/guides/20-performance-optimization/00-query-performance/00-aggregating-index.md
docs/guides/20-performance-optimization/00-query-performance/_category_.json
docs/guides/20-performance-optimization/00-query-performance/index.md
docs/guides/20-performance-optimization/_category_.json
docs/guides/20-performance-optimization/index.md

add query performance: aggregating index to guides

---

docs/sql-reference/00-sql-reference/20-system-tables/system-locks.md
docs/sql-reference/00-sql-reference/index.md
docs/sql-reference/10-sql-commands/00-ddl/01-table/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/04-stream/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/06-clusterkey/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/07-aggregating-index/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/08-share-endpoint/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/08-share/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/10-udf/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/11-external-function/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/12-mask-policy/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/12-network-policy/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/13-connection/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/13-file-format/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/14-transaction/_category_.json
docs/sql-reference/10-sql-commands/00-ddl/14-transaction/index.md
docs/sql-reference/10-sql-commands/00-ddl/14-transaction/show-locks.md

- added SHOW LOCKS
- added system.locks

docs: show locks

---

docs/guides/10-deploy/09-upgrade/10-compatibility.md

refactor: add milestone meta-service versions

---

docs/sql-reference/00-sql-reference/index.md
docs/sql-reference/20-sql-functions/index.md
src/theme/DocBreadcrumbs/Items/Home/index.js

refactor: breadcrums

---

.github/workflows/docs-commit.translate.yaml
.github/workflows/docs.translate.yaml

- Change the model to the best model, gpt-4 turbo with a 128k context window, and cheaper than gpt 4.
- Optimize the prompt words to ensure that they can understand databases and SQL.
- Allow translation based on commit files diff to reduce manual intervention.

ci: optimize the prompts and use the best model.

---

docs/sql-reference/20-sql-functions/10-semi-structured-functions/json-path-match.md

Fixed: https://github.com/datafuselabs/databend-docs/issues/307

docs: fix JSON_PATH_MATCH

---

docs/sql-reference/10-sql-commands/00-ddl/02-user/23-grant-ownership.md
docs/sql-reference/10-sql-commands/00-ddl/02-user/24-revoke-ownership.md
docs/sql-reference/10-sql-commands/00-ddl/02-user/index.md

docs: grant ownership + revoke ownership

---

docs/guides/40-load-data/00-stage/index.md
docs/guides/40-load-data/02-load-db/index.md
docs/guides/40-load-data/04-transform/index.md

* add index for transform
* refine `Loading Data with Tools` to make is simple

guides: add index for transform

---

docs/guides/56-security/access-control.md
docs/sql-reference/10-sql-commands/00-ddl/00-database/show-databases.md
docs/sql-reference/10-sql-commands/00-ddl/01-table/show-tables.md

- updated SHOW DATABASES for `FULL` parameter.
- updated SHOW TABLES for `FULL` parameter.
- refactored description of ownership: _The ownership of an object is assigned to the current role of the user who creates it. Users who share the same role also have ownership of the object and can subsequently grant this ownership to other roles._

docs: ownership updates

---

docs/guides/55-performance/cluster-key.md

added "selecting cluster key" section.

docs: selecting cluster key

---

src/theme/Footer/index.js
src/theme/SearchBar/init-modal.module.scss

fix: Search modal dark bugs

---

docs/guides/10-deploy/03-deploying-local.md

change lo ip to  Lan ip for dev env

docs: Change lo ip to  Lan ip for dev env

---

docs/guides/10-deploy/13-node-config/02-query-config.md

add allow_insecure and file_limit

docs: add allow_insecure and file_limit

---

docs/sql-reference/00-sql-reference/51-connect-parameters.md
docs/sql-reference/10-sql-commands/00-ddl/03-stage/01-ddl-create-stage.md

Added Hugging face for creating external stage.

docs: Hugging face

---

docs/sql-reference/20-sql-functions/05-datetime-functions/date-format.md

Fixes: https://github.com/datafuselabs/databend/issues/14369

docs: Update date_format function

---

docs/guides/10-deploy/13-node-config/02-query-config.md

refactor: https://github.com/datafuselabs/databend-docs/pull/381

docs: refactor description for allow_insecure & file_limit

---

docs/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-create-function.md
docs/sql-reference/20-sql-functions/03-conditional-functions/greatest.md
docs/sql-reference/20-sql-functions/03-conditional-functions/if.md
docs/sql-reference/20-sql-functions/03-conditional-functions/ifnull.md
docs/sql-reference/20-sql-functions/03-conditional-functions/in.md
docs/sql-reference/20-sql-functions/03-conditional-functions/index.md
docs/sql-reference/20-sql-functions/03-conditional-functions/is-distinct-from.md
docs/sql-reference/20-sql-functions/03-conditional-functions/is-not-null.md
docs/sql-reference/20-sql-functions/03-conditional-functions/is-null.md
docs/sql-reference/20-sql-functions/03-conditional-functions/least.md
docs/sql-reference/20-sql-functions/03-conditional-functions/nullif.md

Split Conditional functions into individual pages.

docs: Conditional functions

---

docs/guides/00-overview/index.md

refine the guides index

---

docs/guides/57-data-management/01-data-lifecycle.md
docs/guides/57-data-management/02-data-recovery.md
docs/guides/57-data-management/03-data-protection.md
docs/guides/57-data-management/_category_.json
docs/guides/57-data-management/index.md

add data management to guides

---

docs/guides/00-overview/02-faq.md

databend , mysql, oracle  data type fit

data type fit

---

docs/sql-reference/10-sql-commands/00-ddl/00-database/ddl-drop-database.md
docs/sql-reference/10-sql-commands/00-ddl/00-database/undrop-database.md
docs/sql-reference/10-sql-commands/00-ddl/01-table/21-ddl-undrop-table.md

Add UNDROP DATABASE.
Fixed: https://github.com/datafuselabs/databend-docs/issues/412

docs: undrop db

---

docs/guides/10-deploy/12-upgrade/10-compatibility.md

https://github.com/datafuselabs/databend/issues/14422

add query compact doc

---

docs/sql-reference/20-sql-functions/03-conditional-functions/ifnull.md
docs/sql-reference/20-sql-functions/03-conditional-functions/nvl.md
docs/sql-reference/20-sql-functions/03-conditional-functions/nvl2.md

docs: nvl + nvl2

---

docs/sql-reference/10-sql-commands/20-query-syntax/01-query-select.md

Fixed https://github.com/datafuselabs/databend-docs/issues/406

docs: fixed issue #406

---

docs/cn/sql-reference/10-sql-commands/50-administration-cmds/show-functions.md
docs/sql-reference/00-sql-reference/20-system-tables/system-functions.md
docs/sql-reference/00-sql-reference/20-system-tables/system-user-functions.md
docs/sql-reference/10-sql-commands/50-administration-cmds/show-functions.md
docs/sql-reference/10-sql-commands/50-administration-cmds/show-user-functions.md

Related to https://github.com/datafuselabs/databend/pull/14471 and https://github.com/datafuselabs/databend/pull/14440 , They will be included in the tag 1.2.315 or later, but there is no release yet, so I will open a draft PR first.
Add
- show user functions
- system.user_functions
Update
- show functions
- system.functions

docs: add show user functions and system.user_functions

---

.github/workflows/links-fail-fast.yaml
.github/workflows/links.yaml
lychee.toml

- Daily testing
- Fail Fast testing for PR and Push
Fixes: #273

chore: try to add lychee action to check links

---

docs/guides/30-sql-clients/01-jdbc/index.md

docs: Update index.md

---

.github/workflows/docs.translate.dir.yaml

- add support for json files (the extension specified on the input file side will be retained)

chore: support json files

---

docs/cn/guides/00-overview/02-community/01-rfcs/20220704-presign.md
docs/cn/guides/40-load-data/02-load-db/flink-cdc.md
docs/cn/guides/60-visualize/grafana.md
docs/cn/guides/70-monitor/tools/sentry.md
docs/en/guides/00-overview/02-community/01-rfcs/20220704-presign.md
docs/en/guides/60-visualize/grafana.md
docs/en/guides/70-monitor/tools/sentry.md
lychee.toml

docs: fix links

---

docs/cn/guides/10-deploy/01-deploying-databend.md
docs/en/guides/10-deploy/01-deploying-databend.md
docs/public/templates/deploying-databend-common.md
src/components/EEFeature/index.tsx
src/components/GetLatest/index.js
src/components/LanguageDocs/index.tsx
src/hooks/useGetReleases.ts

How to use:
```js
import LanguageDocs from '@site/src/components/LanguageDocs';
<LanguageDocs
cn=
{
<>
a. Create a folder named `databend` in the directory `/usr/local`.
b. Download and extract the latest Databend release for your platform from [GitHub Release](https://github.com/datafuselabs/databend/releases):
</>
}
en=
{
<>
a. Create a folder named `databend` in the directory `/usr/local`.
b. Download and extract the latest Databend release for your platform from [GitHub Release](https://github.com/datafuselabs/databend/releases):
</>
}
/>
```

feat: add LanguageDocs Comps

---

docs/public/templates/deploying-databend-common.md

chore(mark): remove macOS curl links

---

docs/en/sql-reference/10-sql-commands/30-query-operators/json.md

added json delete operator `-`.

docs: json delete operator

---

docs/en/sql-reference/10-sql-commands/10-dml/dml-copy-into-table.md

added an example for `disable_variant_check` and updated the parameter description.

docs: disable_variant_check for copy into

---

docs/en/guides/56-security/password-policy.md

Fix: https://github.com/datafuselabs/databend-docs/issues/433

docs: updated password policy examples

---

docs/en/guides/56-security/access-control.md
docs/en/sql-reference/00-sql-reference/41-access-control-privileges.md

1. add ownership privilege description
2. add some note about manage ownership

feat: add some doc about ownership privilege

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/20-ddl-drop-table.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/91-vacuum-drop-table.md

https://github.com/datafuselabs/databend/pull/14402

Remove drop table [ALL] and vacuum drop table retain N hours

---

docs/en/guides/10-deploy/01-deploying-databend.md

Explained how to obtain the `credential` for GCS deploy.

docs: gcs credentials

---

docs/en/guides/40-load-data/04-transform/05-data-load-transform.md
docs/en/sql-reference/10-sql-commands/10-dml/dml-copy-into-table.md

added COPY INTO syntax for data transformation to the COPY INTO reference page.

docs: copy into updates

---

docs/cn/guides/30-sql-clients/00-bendsql/index.md
docs/en/guides/30-sql-clients/00-bendsql/index.md

- add notes for toolchain and command installation.
- Move to the end, not recommended for newcomers to try using cargo.

docs(bendsql): install by cargo

---

docs/cn/guides/10-deploy/01-deploy/01-non-production/00-deploying-local.md
docs/cn/guides/10-deploy/01-deploy/01-non-production/01-deploying-databend.md
docs/cn/guides/10-deploy/01-deploy/02-production/10-metasrv-deploy.md

Related #600 #602 
01-deploying-databend.md has not been fully updated and will be done in another PR.

docs(cn): follow en site changes

---

docs/en/sql-reference/10-sql-commands/20-query-syntax/qualify.md
docs/en/sql-reference/20-sql-functions/08-window-functions/row-number.md

Fixed: https://github.com/datafuselabs/databend-docs/issues/673

docs: qualify query syntax

---

docs/en/sql-reference/10-sql-commands/00-ddl/05-view/ddl-drop-view.md
docs/en/sql-reference/10-sql-commands/00-ddl/05-view/desc-view.md
docs/en/sql-reference/10-sql-commands/00-ddl/05-view/show-views.md

added show views + desc view functions.

docs: show views + desc view

---

docs/en/sql-reference/10-sql-commands/10-dml/dml-insert.md

- added a unified syntax
- added description for `OVERWRITE`
- refactored the examples

docs: insert

---

docs/en/sql-reference/20-sql-functions/05-datetime-functions/to-timestamp.md

added doc for https://github.com/datafuselabs/databend/pull/15131

docs: to_timestamp timezone

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/60-optimize-table.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/91-vacuum-table.md
docs/en/sql-reference/10-sql-commands/20-query-syntax/03-query-at.md

Added doc for https://github.com/datafuselabs/databend/pull/15116
Fixes: https://github.com/datafuselabs/databend-docs/issues/700

docs: stream for time travel

---

docs/en/guides/40-load-data/05-continuous-data-pipelines/01-stream.md
docs/en/guides/55-performance/03-fulltext-index.md
docs/en/sql-reference/10-sql-commands/00-ddl/17-inverted-index/index.md

Updated full-text search guide with more detailed explanations.

docs: Fulltext search guide updates

---

docs/en/developer/00-drivers/01-python.md

- Add `secure=True` in py cloud dsn

fix: add secure param in py cloud dsn

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/90-alter-table-comment.md

Added doc for ALTER TABLE COMMENT.

docs: alter table comment

---

docs/en/guides/10-deploy/01-deploy/02-production/10-metasrv-deploy.md

Added more details, such as commands, parameter values, so the guide now gets easy to follow.

docs: cluster deployment updates

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/90-alter-table-column.md

Updated doc for https://github.com/datafuselabs/databend/pull/15217

docs: add comment with ALTER TABLE COLUMN

---

docs/en/developer/00-drivers/00-golang.md
docs/en/developer/00-drivers/03-jdbc.md

fixes: https://github.com/datafuselabs/databend-docs/issues/726

docs: go & jdbc data type mappings

---

docs/en/sql-reference/10-sql-commands/00-ddl/02-user/01-user-create-user.md
docs/en/sql-reference/10-sql-commands/00-ddl/02-user/02-user-show-users.md
docs/en/sql-reference/10-sql-commands/00-ddl/02-user/03-user-alter-user.md

added doc for https://github.com/datafuselabs/databend/pull/15249

docs: enable or disable user

---

docs/en/guides/30-sql-clients/00-bendsql/index.md

Added bendsql cmds:
| Command                   | Description                       |
|---------------------------|-----------------------------------|
| `!exit`                   | Exits BendSQL.                    |
| `!quit`                   | Exits BendSQL.                    |
| `!configs`                | Displays current BendSQL settings.|
| `!set <setting> <value>`  | Modifies a BendSQL setting.       |
| `!source <sql_file>`      | Executes a SQL file.              |

docs: bendsql commands

---

docs/en/sql-reference/20-sql-functions/00-array-functions/_category_.json
docs/en/sql-reference/20-sql-functions/20-map-functions/_category_.json
docs/en/sql-reference/20-sql-functions/20-map-functions/index.md
docs/en/sql-reference/20-sql-functions/20-map-functions/map-keys.md
docs/en/sql-reference/20-sql-functions/20-map-functions/map-values.md
docs/en/sql-reference/20-sql-functions/index.md

fix: https://github.com/datafuselabs/databend-docs/issues/743

feat: add map function docs

---

docs/en/guides/30-sql-clients/00-bendsql/index.md

docs: bendsql settings

---

docs/en/sql-reference/10-sql-commands/20-query-syntax/01-query-select.md
docs/en/sql-reference/10-sql-commands/20-query-syntax/top.md

added doc for `top <n>` syntax.

docs: top n

---

docs/en/sql-reference/10-sql-commands/00-ddl/17-inverted-index/create-inverted-index.md
docs/en/sql-reference/20-sql-functions/21-search-functions/_category_.json
docs/en/sql-reference/20-sql-functions/21-search-functions/index.md
docs/en/sql-reference/20-sql-functions/21-search-functions/match.md
docs/en/sql-reference/20-sql-functions/21-search-functions/query.md
docs/en/sql-reference/20-sql-functions/21-search-functions/score.md
docs/en/sql-reference/20-sql-functions/index.md

feat: add search function docs

---

docs/cn/guides/40-load-data/05-continuous-data-pipelines/01-stream.md
docs/en/guides/40-load-data/05-continuous-data-pipelines/01-stream.md

The result of example statement is not correct

fix: stream doc

---

docs/cn/guides/10-deploy/04-references/02-node-config/02-query-config.md
docs/cn/sql-reference/00-sql-reference/51-connect-parameters.md
docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md
docs/en/sql-reference/00-sql-reference/51-connect-parameters.md

* remove `endpoint_url` for gcs
* make the connection parameters as table and add examples

remove endpoint_url for gcs and make the connection para as table tabs

---

docs/en/sql-reference/10-sql-commands/00-ddl/04-stream/show-streams.md

SHOW STREAMS now has an updated output.

docs: show streams updates

---

docs/en/sql-reference/10-sql-commands/50-administration-cmds/02-set-global.md
docs/en/sql-reference/10-sql-commands/50-administration-cmds/02-unset.md

added the `SESSION` parameter to the UNSET command.

docs: unset session

---

docs/en/guides/40-load-data/05-continuous-data-pipelines/01-stream.md
docs/en/sql-reference/10-sql-commands/20-query-syntax/with-consume.md

Added query syntax WITH CONSUME.

docs: with consume

---

docs/en/guides/10-deploy/02-upgrade/10-compatibility.md

refactor: udpate meta-service compat change

---

docs/cn/guides/40-load-data/02-load-db/tapdata.md
docs/cn/guides/90-community/02-rfcs/20220805-json-optimization.md
docs/en/guides/40-load-data/02-load-db/tapdata.md
docs/en/guides/90-community/02-rfcs/20220805-json-optimization.md

chore: fix links

---

docs/en/guides/56-security/access-control/01-privileges.md

https://github.com/datafuselabs/databend/pull/15634

add database ownership note

---

docs/en/sql-reference/10-sql-commands/00-ddl/02-user/04-user-set-2nd-roles.md
docs/en/sql-reference/10-sql-commands/00-ddl/02-user/22-show-grants.md
docs/en/sql-reference/20-sql-functions/17-table-functions/index.md
docs/en/sql-reference/20-sql-functions/17-table-functions/show-grants.md

- added new syntax: 
`SHOW GRANTS ON { STAGE | TABLE | DATABASE | UDF } <object_name> [ LIKE '<pattern>' | WHERE <expr> | LIMIT <limit> ]`
- added new table func: `SHOW_GRANTS`

docs: show grants updates

---

docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md

Fix doc bug: https://github.com/datafuselabs/databend-docs/issues/830

docs: fix bug 

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/90-alter-table-column.md

added a short note about how to add or modify a col comment only. 
Fixes: https://github.com/datafuselabs/databend-docs/issues/835

docs: add or modify col comment

---

docs/en/sql-reference/10-sql-commands/10-dml/dml-replace.md

Fixes: https://github.com/datafuselabs/databend-docs/issues/829

docs: replace into bug

---

docs/en/guides/54-query/00-cte.md

Updated the CTE guide for recursive CTEs.

docs: recursive cte

---

docs/en/developer/00-drivers/01-python.md
docs/en/guides/54-query/03-udf.md

Fixes: https://github.com/datafuselabs/databend-docs/issues/820

docs: python udf

---

docs/en/guides/00-overview/index.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/92-attach-table.md

Attach Table now only supports for READ-ONLY mode.

docs: attach table read-only

---

docs/en/guides/10-deploy/02-upgrade/10-compatibility.md

Doc: update meta-service compatibility

---

docs/en/guides/00-overview/00-editions/00-dce/index.md
docs/en/guides/00-overview/00-editions/01-dee/_category_.json
docs/en/guides/00-overview/00-editions/01-dee/index.md
docs/en/guides/00-overview/00-editions/02-dc/02-editions.md
docs/en/guides/00-overview/00-editions/index.md

added Databend Cloud edition information.

docs: databendcloud editions

---

docs/en/sql-reference/10-sql-commands/50-administration-cmds/rust-backtrace.md

Added system commands as follows:
-- Enable Rust backtraces
SYSTEM ENABLE EXCEPTION_BACKTRACE
-- Disable Rust backtraces
SYSTEM DISABLE EXCEPTION_BACKTRACE

docs: SYSTEM ENABLE / DISABLE EXCEPTION_BACKTRACE

---

docs/en/sql-reference/00-sql-reference/10-data-types/20-data-type-time-date-types.md

Introduced the daylight saving time setting `enable_dst_hour_fix `.

docs: daylight saving time setting

---

README.md

chore: Upgraded readme

---

docusaurus.config.ts
package.json
yarn.lock

https://vercel.com/databend/databend/analytics?environment=all

feat: add vercel-analytics for docs

---

docs/en/sql-reference/20-sql-functions/08-window-functions/first-value.md
docs/en/sql-reference/20-sql-functions/08-window-functions/last-value.md
docs/en/sql-reference/20-sql-functions/08-window-functions/nth-value.md

Updated the `IGNORE | RESPECT NULLS ` option for FIRST_VALUE, LAST_VALUE, and NTH_VALUE.

docs: IGNORE | RESPECT NULLS 

---

docs/en/guides/20-cloud/10-using-databend-cloud/03-monitor.md
docs/en/guides/54-query/05-query-profile.md
docs/en/sql-reference/10-sql-commands/40-explain-cmds/explain.md

Fixes: https://github.com/datafuselabs/databend-docs/issues/1052

docs: query profile guide

---

lychee.toml

ci(lychee): try to fix links

---

docs/en/guides/20-cloud/10-using-databend-cloud/01-worksheet.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/80-analyze-table.md
docs/en/sql-reference/20-sql-functions/16-system-functions/fuse_statistic.md

- added new stat histograms to FUSE_STATISTIC.
- refactored ANALYZE TABLE and updated the examples on the page.

docs: add histograms to FUSE_STATISTIC

---

docs/en/sql-reference/20-sql-functions/05-datetime-functions/index.md
docs/en/sql-reference/20-sql-functions/05-datetime-functions/months-between.md

added months_between function.

docs: months_between

---

docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-json-array-agg.md
docs/en/sql-reference/20-sql-functions/07-aggregate-functions/index.md

added function JSON_ARRAY_AGG.

docs: JSON_ARRAY_AGG

---

docs/en/sql-reference/10-sql-commands/50-administration-cmds/02-set-global.md
docs/en/sql-reference/10-sql-commands/50-administration-cmds/02-unset.md

https://github.com/datafuselabs/databend/pull/16214

docs: modify unset doc

---

docs/en/guides/00-overview/00-editions/02-dc/00-architecture.md
docs/en/guides/90-community/02-rfcs/20220725-cache.md

separation of storage and **compute**.

docs: computation 2 compute

---

docs/en/guides/31-visualize/grafana.md

fix: links

---

docs/en/guides/40-load-data/02-load-db/kafka.md

Introducing databend-kafka-connect.

docs: databend-kafka-connect

---

docs/en/guides/55-performance/03-fulltext-index.md
docs/en/sql-reference/20-sql-functions/10-search-functions/match.md
docs/en/sql-reference/20-sql-functions/10-search-functions/query.md

- added new options `fuzziness`, `operator`, and `lenient` to search functions.
- added description about suffix matching for the `<keyword>` parameter. 
- added `<column>:IN [<keyword1>, <keyword2>...]` to the `Query` search function.
- added new examples.

docs: Full-Text Index Updates

---

docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/index.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/jq.md

docs: jq function

---

docs/en/guides/00-overview/00-editions/01-dee/10-enterprise-features.md
docs/en/guides/00-overview/00-editions/02-dc/02-editions.md
src/components/DatabendTable/index.tsx
src/css/markdown.scss
src/pages/download/index.tsx

Here I added a `DatabendTable` Comp that can control the colun's `width`.
```js
import DatabendTable from '@site/src/components/DatabendTable';
<DatabendTable
width={['70%', '15%', '15%']}
thead={['Functionality', 'Databend Community', 'Databend Enterprise']}
tbody={[
['Cluster Mode', '✕', '✓'],
['Materialized Views', '✕', '✓'],
['AI Functions (Sentiment Analysis, Data Annotation, etc.)', '✕', 'HuggingFace Open Source Models'],
['Multi-tenant Data Sharing', '✕', '✓'],
]}
/>
```

fix(styles): adjust tables

---

docs/en/tutorials/load/kafka-bend-ingest-kafka.md

Added raw mode to the bend-ingest-kafka tutorial.

docs: bend-ingest-kafka raw mode

---

docs/en/sql-reference/00-sql-reference/30-table-engines/00-fuse.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/90-alter-table-option.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/show-create-table.md

- added new fuse engine option `data_retention_period_in_hours `
- refactored ALTER TABLE OPTION
- refactored SHOW CREATE TABLE

docs: fuse engine option `data_retention_period_in_hours `

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/90-alter-table-option.md

added `ALTER TABLE [ <database_name>. ]<table_name> UNSET OPTIONS (<options>)`

docs: unset fuse engine options

---

docs/en/sql-reference/20-sql-functions/05-datetime-functions/date-add.md

- added syntax for https://github.com/databendlabs/databend/pull/16530
- added examples.

docs: add week unit for date_add

---

docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-arg-min.md

fix: outputs

---

docs/en/sql-reference/00-sql-reference/42-lambda-expressions.md
docs/en/sql-reference/10-sql-commands/30-query-operators/json.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/index.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-apply.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-distinct.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-except.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-filter.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-insert.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-intersection.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-map.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-overlap.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-reduce.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-array-transform.md

added new json array functions for https://github.com/databendlabs/databend/pull/16571
- JSON_ARRAY_DISTINCT
- JSON_ARRAY_EXCEPT
- JSON_ARRAY_INSERT
- JSON_ARRAY_INTERSECTION
- JSON_ARRAY_OVERLAP
- JSON_ARRAY_REDUCE
- JSON_ARRAY_TRANSFORM, JSON_ARRAY_APPLY, JSON_ARRAY_MAP]
- JSON_ARRAY_FILTER
added new json operator: `||`
added Lambda Expressions.

docs: json array functions

---

docs/en/sql-reference/10-sql-commands/00-ddl/17-dictionary/show-dictionaries.md

added new cmd: SHOW DICTIONARIES.

docs: SHOW DICTIONARIES

---

docs/en/sql-reference/10-sql-commands/00-ddl/02-user/01-user-desc-user.md
docs/en/sql-reference/10-sql-commands/00-ddl/02-user/02-user-show-users.md
docs/en/sql-reference/10-sql-commands/00-ddl/02-user/index.md

- added DESC USER.
- updated examples for SHOW USERS.

docs: DESC USER

---

docusaurus.config.ts
src/theme/Footer/index.tsx

```JS
<script type="application/ld+json">
{`
{
"@context": "https://schema.org",
"@type": "Organization",
"name": "Databend",
"url": "https://www.databend.com/",
"logo": "https://www.databend.com/img/resource/png/light-databend-single.png",
"description": "Databend is a cloud-native, open-source data warehouse platform optimized for data ingestion, AI-driven analytics, and SQL compatibility.",
"sameAs": [
"https://github.com/databendlabs",
"https://github.com/databendcloud",
"https://x.com/DatabendLabs",
"https://www.linkedin.com/company/databendlabs/",
"https://medium.com/@databend",
"https://www.reddit.com/r/DatafuseLabs/",
"https://www.youtube.com/@DatabendLabs",
"https://link.databend.com/join-slack",
"https://aws.amazon.com/marketplace/pp/prodview-6dvshjlbds7b6", …
```

feat: add schema for website SEO

---

docs/en/guides/10-deploy/04-references/02-node-config/01-metasrv-config.md
docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md

The option: file_limit is not effect.
https://github.com/databendlabs/databend/blob/main/src/query/config/src/config.rs#L2084

docs:The correct configuration option is limit

---

docs/en/sql-reference/20-sql-functions/00-array-functions/array-length.md
docs/en/sql-reference/20-sql-functions/00-array-functions/array-size.md

added ARRAY_SIZE as an alias for ARRAY_LENGTH.

docs: ARRAY_SIZE

---

docs/en/sql-reference/20-sql-functions/10-map-functions/map-filter.md
docs/en/sql-reference/20-sql-functions/10-map-functions/map-transform-keys.md
docs/en/sql-reference/20-sql-functions/10-map-functions/map-transform-values.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/index.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-map-filter.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-map-transform-keys.md
docs/en/sql-reference/20-sql-functions/10-semi-structured-functions/json-map-transform-values.md

Added new map lambda functions:
- map_filter
- map_transform_keys
- map_transform_values
- json_map_filter
- json_map_transform_keys
- json_map_transform_values

docs: map lambda functions

---

docs/en/sql-reference/10-sql-commands/20-query-syntax/settings.md
docs/en/sql-reference/10-sql-commands/50-administration-cmds/02-set-global.md
docs/en/sql-reference/10-sql-commands/50-administration-cmds/03-set-var.md

added the SETTINGS clause:
```sql
SETTINGS ( <setting> = <value> [, <setting> = <value>, ...] ) <statement>
```

docs: settings clause

---

docs/en/guides/10-deploy/02-upgrade/10-compatibility.md

chore: update meta-service compatibility doc

---

docs/cn/guides/10-deploy/01-deploy/00-understanding-deployment-modes.md
docs/cn/guides/10-deploy/01-deploy/01-non-production/01-deploying-databend.md
docs/cn/guides/10-deploy/04-references/02-node-config/02-query-config.md

Added support of hw obs back to the CN doc.

docs: add obs back to CN doc

---

docs/en/guides/10-deploy/01-deploy/00-understanding-deployment-modes.md
docs/en/guides/10-deploy/01-deploy/01-non-production/01-deploying-databend.md
docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md

```
some english contents
```
```
一些中文内容
```
cc @soyeric128

chore: test language part

---

docs/en/sql-reference/20-sql-functions/06-string-functions/index.md
docs/en/sql-reference/20-sql-functions/06-string-functions/ltrim.md
docs/en/sql-reference/20-sql-functions/06-string-functions/rtrim.md
docs/en/sql-reference/20-sql-functions/06-string-functions/trim-both.md
docs/en/sql-reference/20-sql-functions/06-string-functions/trim-leading.md
docs/en/sql-reference/20-sql-functions/06-string-functions/trim-trailing.md
docs/en/sql-reference/20-sql-functions/06-string-functions/trim.md

added new trim functions or syntax:
- TRIM
- TRIM_BOTH
- TRIM_LEADING
- TRIM_TRAILING
- LTRIM
- RTRIM

docs: trim functions

---

docs/en/sql-reference/00-sql-reference/20-system-tables/system-databases-with-history.md
docs/en/sql-reference/10-sql-commands/00-ddl/00-database/show-drop-databases.md

- added new ddl: SHOW DROP DATABASES
- added new sys tbl: system.databases_with_history

docs: SHOW DROP DATABASES

---

docs/en/guides/30-sql-clients/00-bendsql/index.md

added shell script install for BendSQL.

docs: bendsql shell script install

---

docs/en/guides/54-query/03-udf.md
docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-show-user-functions.md

- added cmd: SHOW USER FUNCTIONS
- fixed examples in UDF guide.

docs: SHOW USER FUNCTIONS

---

docs/en/sql-reference/10-sql-commands/00-ddl/12-mask-policy/create-mask-policy.md

Now default column type is nullable

chore: mask value type is err

---

docs/en/guides/56-security/masking-policy.md
docs/en/sql-reference/00-sql-reference/20-system-tables/information-schema-tables.md
docs/en/sql-reference/00-sql-reference/20-system-tables/system-databases.md
docs/en/sql-reference/00-sql-reference/20-system-tables/system-tables-with-history.md
docs/en/sql-reference/00-sql-reference/20-system-tables/system-tables.md
docs/en/sql-reference/10-sql-commands/00-ddl/00-database/show-databases.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/show-drop-tables.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/show-tables.md

added missing system tables to General Reference:
- information_schema.tables
- system.databases
- system.tables_with_history
- system.tables

docs: system tables

---

docs/en/guides/10-deploy/01-deploy/02-production/30-metasrv-backup-restore.md

refactor: meta-service backup

---

docs/en/guides/10-deploy/01-deploy/02-production/30-metasrv-backup-restore.md
docs/en/guides/10-deploy/04-references/02-node-config/01-metasrv-config.md

refactor: add databend-meta config

---

docs/cn/guides/10-deploy/04-references/02-node-config/02-query-config.md

fix: close tag

---

docs/en/guides/40-load-data/05-continuous-data-pipelines/01-stream.md

added description about translating UPDATE to DELETE & INSERT.

docs: stream guide updates

---

docs/en/sql-reference/00-sql-reference/20-system-tables/system-temp-tables.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table-external-location.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-temp-table.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-transient-table.md

- added `CREATE TEMP TABLE` cmd.
- added system table `system.temporary_tables`.
- re-organized `CREATE EXTERNAL TABLE` & `TRANSIENT TABLE`.

docs: temporary table

---

docs/cn/guides/40-load-data/02-load-db/tapdata.md
docs/en/guides/40-load-data/02-load-db/tapdata.md

Fix https://github.com/databendlabs/databend-docs/issues/1473

fix: tapdata agent docs

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-temp-table.md
docs/en/sql-reference/20-sql-functions/17-table-functions/fuse-vacuum-temporary-table.md

added tbl func: FUSE_VACUUM_TEMPORARY_TABLE.
```sql
SELECT * FROM FUSE_VACUUM_TEMPORARY_TABLE();
┌────────┐
│ result │
├────────┤
│ Ok     │
└────────┘
```

docs: FUSE_VACUUM_TEMPORARY_TABLE

---

docs/en/sql-reference/20-sql-functions/08-window-functions/last-value.md
docs/en/sql-reference/20-sql-functions/08-window-functions/nth-value.md

Fixed examples for NTH_VALUE & LAST_VALUE.

docs: fix examples

---

docs/en/guides/57-data-management/02-data-recovery.md

docs: add FLASHBACK TABLE link

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table-external-location.md

Fixes the CREATE EXTERNAL TABLE syntax.

docs: fix syntax

---

docs/cn/guides/30-sql-clients/01-jdbc/index.md
docs/en/guides/30-sql-clients/01-jdbc/index.md

Even if I use the old version of jdbc as it is, an error occurred, so I thought it would be better to apply the latest version I applied while working on it to the document, so I corrected it and asked for a pull request.

fix jdbc version upgrade 0.1.6 -> 0.3.4

---

docs/en/sql-reference/00-sql-reference/10-data-types/interval.md
docs/en/sql-reference/10-sql-commands/00-ddl/00-database/undrop-database.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/21-ddl-undrop-table.md

- added description about re-granting ownership after undroping a db or tbl. 
- added description about interval data type ignores the fractional part after the decimal point.

docs: undrop table / db updates

---

docs/en/sql-reference/00-sql-reference/10-data-types/interval.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/_category_.json
docs/en/sql-reference/20-sql-functions/05-interval-functions/epoch.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/index.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-centries.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-days.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-decades.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-hours.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-microseconds.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-millennia.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-milliseconds.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-minutes.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-months.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-seconds.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-weeks.md
docs/en/sql-reference/20-sql-functions/05-interval-functions/to-years.md

- updated interval datatype description.
- added interval functions:
- EPOCH
- TO_CENTURIES
- TO_DAYS
- TO_DECADES
- TO_HOURS
- TO_MICROSECONDS
- TO_MILLENNIA
- TO_MILLISECONDS
- TO_MINUTES
- TO_MONTHS
- TO_SECONDS
- TO_WEEKS
- TO_YEARS

docs: interval functions

---

README.md
docs/cn/guides/90-community/index.md
docs/en/guides/90-community/index.md
docusaurus.config.ts
i18n/en/docusaurus-theme-classic/footer.json
i18n/zh/docusaurus-theme-classic/footer.json
src/components/JoinCommunity/index.tsx

fix: twitter links

---

docs/en/guides/00-overview/index.md

_Welcome to the Databend (pronounced as /ˈdeɪtəˌbɛnd/) documentation. Databend is an affordable, Snowflake-like cloud data warehouse. You can choose to self-host Databend as a completely free and open-source solution, or opt for the convenience of getting started right away with Databend Cloud._

docs: Update Databend Documentation Overview

---

docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/_category_.json
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/alter-warehouse.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/create-warehouse.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/drop-warehouse.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/index.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/rename-warehouse.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/resume-warehouse.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/show-online-nodes.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/show-warehouses.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/suspend-warehouse.md
docs/en/sql-reference/10-sql-commands/00-ddl/19-warehouse/use-warehouse.md

adds warehouse DDL:
- ALTER WAREHOUSE
- CREATE WAREHOUSE
- DROP WAREHOUSE
- RENAME WAREHOUSE
- RESUME WAREHOUSE
- SHOW ONLINE NODES
- SHOW WAREHOUSES
- SUSPEND WAREHOUSE
- USE WAREHOUSE

docs: warehouse ddl

---

docs/en/tutorials/migrate/migrating-from-mysql-with-db-archiver.md

adds a db-archiver tutorial: Migrating from MySQL with db-archiver.

docs: db-archiver tutorial

---

docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md
docs/en/guides/57-data-management/04-data-recycle.md

added local and remote spill storage config.

docs: Spill Data Storage

---

docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-sum.md

SUM now supports for INTERVAL values.

docs: sum updates

---

docs/en/sql-reference/20-sql-functions/05-datetime-functions/date-trunc.md

DATE_TRUNC now supports WEEK as a precision.

docs: DATE_TRUNC updates

---

docs/en/sql-reference/20-sql-functions/05-datetime-functions/extract.md

```sql
-- Extract from an interval
EXTRACT( YEAR | MONTH | WEEK | DAY | HOUR | MINUTE | SECOND | MICROSECOND ｜ EPOCH FROM <interval> )
```

docs: EXTRACT function supports interval

---

docs/en/sql-reference/20-sql-functions/08-window-functions/first-value.md
docs/en/sql-reference/20-sql-functions/08-window-functions/last-value.md
docs/en/sql-reference/20-sql-functions/08-window-functions/nth-value.md

If all values in the window frame are NULL, the function returns NULL even when `IGNORE NULLS` is specified.

docs: window functions updates

---

docs/en/sql-reference/20-sql-functions/16-system-functions/fuse_statistic copy.md

adds table func. FUSE_TIME_TRAVEL_SIZE.

docs: FUSE_TIME_TRAVEL_SIZE

---

docs/en/guides/51-access-data-lake/02-iceberg/iceberg-catalog.md

Updated iceberg ctlg syntax & example:
```sql
CREATE CATALOG <catalog_name>
TYPE=ICEBERG
CONNECTION=(
TYPE='<connection_type>'
ADDRESS='<address>'
WAREHOUSE='<warehouse_location>'
"<connection_parameter>"='<connection_parameter_value>'
"<connection_parameter>"='<connection_parameter_value>'
...
);
```

docs: iceberg ctlg updates

---

docs/en/sql-reference/10-sql-commands/10-dml/dml-update.md

- Added support for updating a table with values from another table:
```sql
UPDATE <target_table>
SET <col_name> = <value> [ , <col_name> = <value> , ... ] -- Set new values  
[ FROM <additional_tables> ] -- Use values from other tables  
[ WHERE <condition> ] -- Filter rows
```
- Updated examples.

docs: update from table

---

docs/en/guides/10-deploy/02-upgrade/10-compatibility.md

chore(meta): add meta-meta compatibility chart svg

---

docs/en/guides/10-deploy/02-upgrade/10-compatibility.md
static/img/deploy/compat-meta-meta-1-2-655.svg

chore(meta): add meta-meta compatibility chart svg local to this site

---

docs/en/sql-reference/20-sql-functions/06-string-functions/regexp-substr.md

added notes based on feedback from a customer.

docs: REGEXP_SUBSTR updates

---

docs/en/sql-reference/10-sql-commands/10-dml/dml-update.md

added the `error_on_nondeterministic_update` setting for the UPDATE cmd.

docs: error_on_nondeterministic_update for update 

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table.md
docs/en/sql-reference/20-sql-functions/18-sequence-functions/nextval.md

Added support for nextval(seq) as a column default value.

docs: nextval(seq) as a column default value

---

docs/en/guides/10-deploy/01-deploy/01-non-production/00-deploying-local.md
docs/en/guides/40-load-data/00-stage/00-what-is-stage.md

- Updated the stage type comparison table. 
- Removed local deployment guide.

docs: stage guide updates

---

docs/en/guides/10-deploy/00-QuickStart/index.md
docs/en/guides/10-deploy/00-QuikStart/index.md

This guide will help you quickly set up Databend, connect to it, and perform a basic data import.
#https://github.com/databendlabs/databend-docs/issues/1828

Doc: Add QuikStart

---

docs/en/guides/56-security/recovery-from-operational-errors.md
docs/en/sql-reference/10-sql-commands/00-ddl/00-database/undrop-database.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/21-ddl-undrop-table.md

Guides --> Security & Reliability --> Recovery from Operational Errors

Recovery from Operational Errors

---

docs/en/sql-reference/20-sql-functions/05-datetime-functions/date-between.md
docs/en/sql-reference/20-sql-functions/05-datetime-functions/index.md

This PR depends on https://github.com/databendlabs/databend/pull/17782:
```sql
DATE_BETWEEN(
YEAR | QUARTER | MONTH | WEEK | DAY | HOUR | MINUTE | SECOND |
DOW | DOY | EPOCH | ISODOW | YEARWEEK | MILLENNIUM,
<start_date_or_timestamp>,
<end_date_or_timestamp>
)
```

docs: date_between

---

docs/en/guides/81-how-databend-works/01-how-databend-fuse-engine-works.md
docs/en/guides/81-how-databend-works/_category_.json
docs/en/guides/81-how-databend-works/index.md

Part of https://github.com/databendlabs/databend-docs/issues/1824

How Fuse Engine Works

---

docs/en/sql-reference/10-sql-commands/00-ddl/17-dictionary/create-dictionary.md

Add: the goal of the dictionary and the usage example

refine: dictionary

---

docs/en/guides/30-sql-clients/00-bendsql/index.md
docs/en/tutorials/connect/connect-to-databend-bendsql.md
docs/en/tutorials/migrate/migrating-from-mysql-with-db-archiver.md

- added the Connecting with BendSQL section to the BendSQL guide.
- updated bendsql tutorial: connecting with Bendsql using  `--host <HOST> --port <PORT>`.

docs: bendsql dsn

---

docs/en/sql-reference/10-sql-commands/10-dml/dml-copy-into-table.md

Now the COPY INTO is stable, we don't modify too often, we can make it more easy to use.

refine: COPY INTO <table>

---

docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-group-concat.md
docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-listagg.md

- Added LISTAGG (Aggregate Function + Window Function).
- Marked GROUP_CONCAT and STRING_AGG as an alias of LISTAGG.

docs: LISTAGG

---

docs/en/guides/56-security/access-control/01-privileges.md
docs/en/sql-reference/10-sql-commands/00-ddl/00-database/ddl-use-database.md

- added  `USAGE` privilege for db.
- added an important notes for `USE DATABASE`.

docs: db usage privilege

---

docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md
docs/en/guides/51-access-data-lake/02-iceberg.md

- explained how to get started with the iceberg quick start project: https://github.com/databendlabs/iceberg-quick-start
- added a new cache configuration parameter: `iceberg_table_meta_count`.

docs: iceberg quick start

---

docs/en/sql-reference/00-sql-reference/30-table-engines/00-fuse.md

- add `enable_auto_vacuum` and `data_retention_num_snapshots_to_keep`
- add sql example

fuse: add enable_auto_vacuum and data_retention_num_snapshots_to_keep

---

docs/en/sql-reference/00-sql-reference/31-system-tables/_category_.json
docs/en/sql-reference/00-sql-reference/31-system-tables/index.md

feat: add system tables index.md

---

docs/en/tutorials/migrate/index.md
docs/en/tutorials/migrate/migrating-from-mysql-with-addax.md
docs/en/tutorials/migrate/migrating-from-mysql-with-datax.md
docs/en/tutorials/migrate/migrating-from-mysql-with-db-archiver.md
docs/en/tutorials/migrate/migrating-from-mysql-with-debezium.md
docs/en/tutorials/migrate/migrating-from-mysql-with-flink-cdc.md
docs/en/tutorials/migrate/migrating-from-mysql-with-kafka-connect.md
docs/en/tutorials/migrate/migrating-from-snowflake.md

- re-org the content of the migrating
- add migrating from MySQL with Kafka connect

re-org the migrating from other database to databend

---

lychee.toml

fix: ignore 403 link's checking

---

docs/en/sql-reference/10-sql-commands/00-ddl/04-sequence/desc-sequence.md
docs/en/sql-reference/10-sql-commands/00-ddl/04-sequence/show-sequences.md
docs/en/sql-reference/10-sql-commands/00-ddl/index.md

- SHOW SEQUENCES and DESC SEQUENCE
- refine the DDL index.md

sequence: SHOW SEQUENCES and DESC SEQUENCE

---

docs/en/guides/51-access-data-lake/_category_.json
docs/en/guides/51-access-data-lake/index.md
docs/en/guides/51-ai-functions/01-external-functions.md
docs/en/guides/51-ai-functions/02-built-in-functions.md
docs/en/guides/51-ai-functions/_category_.json
docs/en/guides/51-ai-functions/index.md

- refine data lake to Data Lakehouse
- refine AI Capabilities to Databend AI and ML

Databend Data Lakehouse and Databend AI&ML

---

docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md

update storage network config doc

chore: update storage network config doc

---

lychee.toml

chore: add unchecked 500...599

---

docs/en/guides/54-query/00-cte.md
docs/en/guides/54-query/01-groupby/_category_.json
docs/en/guides/54-query/02-join.md
docs/en/guides/54-query/02-sequences.md
docs/en/guides/54-query/_category_.json
docs/en/guides/54-query/index.md
docs/en/guides/55-performance/00-cluster-key.md
docs/en/guides/55-performance/01-virtual-column.md
docs/en/guides/55-performance/02-aggregating-index.md
docs/en/guides/55-performance/03-fulltext-index.md
docs/en/guides/55-performance/index.md
docs/en/guides/55-performance/ngram-index.md
docs/en/guides/55-performance/query-result-cache.md
docs/en/guides/57-data-management/01-data-lifecycle.md

- **Terminology Consistency**
- Renames section and page titles for uniformity (e.g., “CTEs” → “CTE”, “JOINs” → “JOIN”, “GROUP BYs” → “GROUP BY”).
- Changes “Query Structures” to “Queries” across navigation and content.
- **Major Additions**
- **Cluster Key:** Expanded with more details, examples, benefits, and best practices.
- **Virtual Column:** Enhanced with automatic JSON acceleration details, workflows, and configuration.
- **Aggregating Index:** Expanded to include benefits, refresh strategies, and usage examples.
- **Full-Text Index:** Added clear use cases, examples, best practices, and advanced search features.
- **Ngram Index:** Clarified distinction from full-text, added setup guidance and best practices.
- **Query Result Cache:** Improved explanation of cache conditions, …

refine: guides query and performance part

---

.github/workflows/prompt.txt
docs/en/guides/20-cloud/10-using-databend-cloud/01-warehouses.md
docs/en/guides/20-cloud/_category_.json
docs/en/guides/20-cloud/index.md
docs/en/guides/30-sql-clients/_category_.json
docs/en/guides/30-sql-clients/index.md

- improve warehouse connection
- improve databend connect

warehouse: add more for connect

---

docs/en/guides/10-deploy/_category_.json
docs/en/guides/10-deploy/index.md
docs/en/guides/20-cloud/10-using-databend-cloud/01-warehouses.md

- Self-Hosted Databend to Databend Self-Hosted
- Improve the deploy index.md

improve databend self-hosted

---

docusaurus.config.ts
site-config.ts
site-redirects.ts
static/icons/x.ts

Extract the "site config" module

feat: enhance site-config

---

docs/en/guides/51-access-data-lake/02-iceberg.md
docs/en/sql-reference/10-sql-commands/00-ddl/18-procedure/create-procedure.md
docs/en/sql-reference/20-sql-functions/03-conditional-functions/decode.md

1. add decode function descr
2. improve procedure & iceberg docs

docs: add decode function descr

---

docs/en/sql-reference/10-sql-commands/00-ddl/01-table/91-alter-table-connection.md
docs/en/sql-reference/10-sql-commands/00-ddl/01-table/index.md

- add alter table connection
- refine the tables index.md

add alter table connection

---

docs/en/sql-reference/20-sql-functions/06-string-functions/char.md
docs/en/sql-reference/20-sql-functions/06-string-functions/index.md

- Detailed description and examples for CHAR/CHR string function, update its docs for usage, return type, remarks, and usage.
Fix https://github.com/databendlabs/databend-docs/issues/2379

update string CHAR func

---

docs/en/guides/54-query/03-udf.md
docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-bool-and.md
docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-bool-or.md

feat(query): add bool_and bool_or and udf wasm docs

feat(query): add bool_and bool_or and udf wasm docs

---

docs/en/guides/10-deploy/02-upgrade/10-compatibility.md
docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md

Add docs for https://github.com/databendlabs/databend/pull/18194

docs: add external system_history

---

docs/en/developer/20-community/00-contributor/04-how-to-profiling.md
docs/en/sql-reference/10-sql-commands/40-explain-cmds/explain-perf.md

add docs for https://github.com/databendlabs/databend/pull/18251

docs: add `explain perf`

---

docs/en/guides/54-query/02-join.md

for: https://github.com/databendlabs/databend/pull/18238

docs: add docs for 'ASOF JOIN'

---

docs/en/developer/00-drivers/03-jdbc.md

Add databend-jdbc connection docs.

fix: update 03-jdbc.md

---

docs/en/sql-reference/20-sql-functions/05-datetime-functions/date-trunc.md
docs/en/sql-reference/20-sql-functions/05-datetime-functions/index.md
docs/en/sql-reference/20-sql-functions/05-datetime-functions/time-slice.md

1. Add doc about function time_slice
2. format function index.md

chore: add doc about time_slice
