- docs/doc/10-deploy/10-node-config/01-metasrv-config.md
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/
- Bug Fix
> fix: the unit should be byte for snasphot_chunk_size

- docs/doc/10-deploy/09-upgrade/10-compatibility.md
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/
> Fix: the meta server version introducing install_snapshot_v1 should be 1.2.212

- docs/guides/10-deploy/09-upgrade/10-compatibility.md
> fix: meta compatibility: `1.2.53` introduces incompatible snapshot format

- docs/sql-reference/00-sql-reference/50-file-format-options.md
added MISSING_FIELD_AS for parquet format.
> docs: MISSING_FIELD_AS for parquet

- docs/developer/10-drivers/00-golang.md
- docs/developer/10-drivers/01-python.md
- docs/developer/10-drivers/02-nodejs.md
- docs/developer/10-drivers/03-jdbc.md
- docs/developer/10-drivers/04-rust.md
I didnt replace the connection strings with their format like "<your_useranme>:<your_passcode> ..." as they are in the tutorials where users can follow along by just copy & paste (the first step in the tutorials creates the sample user "user1" )
Instead, I added the following notes right above the connection string in the code as a reminder:
_// Connecting to a local Databend with a SQL user named 'user1' and password 'abc123' as an example.
// Feel free to use your own values while maintaining the same format._
> docs: added note to connection string

- docs/sql-reference/10-sql-commands/00-ddl/02-user/02-user-show-users.md
- docs/sql-reference/10-sql-commands/00-ddl/02-user/03-user-alter-user.md
- docs/sql-reference/10-sql-commands/00-ddl/02-user/04-user-set-role.md
- docs/sql-reference/10-sql-commands/00-ddl/02-user/04-user-show-roles.md
- docs/sql-reference/10-sql-commands/00-ddl/02-user/index.md
- added `SET ROLE` command.
- added `ALTER USER <name> WITH DEFAULT_ROLE = '<role_name>'` syntax for setting default role.
- refactored `SHOW ROLES` command.
> docs: set role and default role

- .github/workflows/docs-commit.translate.yaml
Uppercase means selected, lowercase means excluded. For now, we only need to exclude deletion to work well. I made a mistake before.
It is best not to trigger CI for release-related logs. We should allow each language to directly reuse the English version.
> chore(ci): fix filter

- docs/developer/00-drivers/01-python.md
The information in the table is about the databend-driver Python package, and I mistakenly introduced&labeled it. Since we have not officially introduced it in the documentation yet, we need to remove this table.
> docs(drivers): remove wrong info about databend-py

- docs/sql-reference/00-sql-reference/50-file-format-options.md
- quote: ["'", """, "`"]
- escape: ["\", ""]
- field_delimiter/record_delimiter: one-byte, non-alphanumeric
> docs: file format options updates

- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/90-alter-table-column.md
- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/90-alter-table-option.md
Updated COLUMN as an optional keyword in the ALTER TABLE syntax. 
I guess this pr fixes: https://github.com/datafuselabs/databend-docs/issues/111
> docs: optional column for alter table

- docs/en/sql-reference/00-sql-reference/10-data-types/43-data-type-variant.md
Updated examples: Values can be accessed by the field name using either square brackets or colon notation.
> docs: Variant updates

- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/91-vacuum-table.md
- added new syntax: VACUUM TABLE <table_name> [ DRY RUN [SUMMARY] ]
- updated data retention description.
> docs: dry run summary

- docs/en/sql-reference/10-sql-commands/00-ddl/04-stream/create-stream.md
- Updated the syntax for the `AT => SNAPSHOT` and `AT => TIMESTAMP` parameters.
- Added related examples.
> docs: AT parameter for CREATE STREAM

- docs/en/guides/40-load-data/04-transform/00-querying-parquet.md
- docs/en/guides/40-load-data/04-transform/01-querying-csv.md
- docs/en/guides/40-load-data/04-transform/02-querying-tsv.md
- docs/en/guides/40-load-data/04-transform/03-querying-ndjson.md
query parquet, csv, tsv, ndjson add files parameter
> docs: add files parameter

- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/show-tables.md
- docs/en/sql-reference/10-sql-commands/00-ddl/05-view/show-views.md
1. added a note: _Starting from version 1.2.415, the SHOW TABLES command no longer includes views in its results. To display views, use SHOW VIEWS instead._
2. Updated syntax & examples for SHOW VIEWS.
> docs: show views updates

- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table.md
Fixed description for the CREATE TABLE ... EXTERNAL_LOCATION command.
> docs: fix description for CREATE TABLE ... EXTERNAL_LOCATION

- docs/en/sql-reference/00-sql-reference/20-system-tables/system-temp-files.md
- docs/en/sql-reference/00-sql-reference/20-system-tables/system-user-functions.md
- docs/en/sql-reference/10-sql-commands/50-administration-cmds/03-show-settings.md
- added a note to show settings: 
`As Databend updates the system settings every now and then, this example may not show the most recent results. To view the latest system settings in Databend, please execute SHOW SETTINGS; within your Databend instance.`
- fixed broken links.
> docs: show settings note

- docs/en/sql-reference/10-sql-commands/00-ddl/18-sequence/create-sequence.md
added a note:
`A sequence in Databend currently starts with 1 and increments by 1. While sequences guarantee unique values, they do not ensure contiguity (i.e., without gaps).`
> docs: sequence updates

- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table.md
added a caution about transient table:
`Concurrent modifications (including write operations) on transient tables may cause data corruption, making the data unreadable. This defect is being addressed. Until fixed, please avoid concurrent modifications on transient tables.`
> docs: transient table caution

- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/10-ddl-create-table.md
- docs/en/sql-reference/20-sql-functions/05-datetime-functions/try-to-timestamp.md
- Updated the syntax: `TRY_TO_TIMESTAMP(<expr>, <pattern>)`
- Added more examples. 
- Fixes https://github.com/datafuselabs/databend-docs/issues/841
> docs: TRY_TO_TIMESTAMP

- docs/en/guides/10-deploy/02-upgrade/10-compatibility.md
> chore: update meta compatibility: removed V001

- docs/cn/guides/90-community/00-contributor/00-building-from-source.md
- docs/en/guides/90-community/00-contributor/00-building-from-source.md
The current brew no longer supports brew install clang. Need to use brew install llvm.
> docs: Update Clang Installation Method

- docs/en/guides/40-load-data/04-transform/03-querying-orc.md
- docs/en/guides/40-load-data/04-transform/index.md
- docs/en/sql-reference/00-sql-reference/50-file-format-options.md
- added orc as an input format to the reference "Input & Output File Formats".
- deprecated XMl as an input format.
- added a tutorial explaining how to query a staged orc file.
> docs: orc file format

- docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md
added new parameters in databend-query.toml:
- `aggregate_spilling_memory_ratio`
- `join_spilling_memory_ratio`
- `max_running_queries`
> docs: query parameters

- docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md
added query parameters in databend-query. toml
- `data_retention_time_in_days_max`
- `root`
Fixes: https://github.com/datafuselabs/databend-docs/issues/597
> docs: data_retention_time_in_days_max & root parameters

- docs/en/guides/40-load-data/05-continuous-data-pipelines/00-pipeline.md
There is no limit on the number of pipelines you can create for your organization. However, please remember that a pipeline requires a warehouse to run, so running a pipeline will incur costs. For more information about warehouse pricing, see [Warehouse Pricing](/guides/cloud/manage/pricing#warehouse-pricing).
> docs: pipeline note

- docs/en/sql-reference/10-sql-commands/00-ddl/02-user/01-user-create-user.md
- docs/en/sql-reference/10-sql-commands/00-ddl/02-user/03-user-alter-user.md
- added MUST_CHANGE_PASSWORD to CREATE USER & ALTER USER. 
- added `ALTER USER USER() IDENTIFIED BY '<new_password>'`:  This allows users to change their own password.
ps. MUST_CHANGE_PASSWORD does not work well with the latest version of bendsql yet, so i didnt include any examples.
Examples will be added once the fix is applied. 
--
Updated: added an example @b41sh
> docs: MUST_CHANGE_PASSWORD

- docs/en/guides/56-security/access-control/03-ownership.md
- docs/en/sql-reference/10-sql-commands/00-ddl/02-user/10-grant.md
- docs/en/sql-reference/10-sql-commands/00-ddl/02-user/11-revoke.md
refactored the ownership topic.
> docs: ownership updated

- docs/en/sql-reference/20-sql-functions/00-array-functions/array-sort.md
- added new examples:
This example shows the array sorted in ascending order by default, with the elements arranged from smallest to largest:
```sql
SELECT ARRAY_SORT([1, 4, 3, 2]);
-[ RECORD 1 ]-----------------------------------
array_sort([1, 4, 3, 2]): [1,2,3,4]
```
This example sorts the array in descending order, arranging the elements from largest to smallest:
```sql
SELECT ARRAY_SORT([1, 4, 3, 2], 'DESC');
-[ RECORD 1 ]-----------------------------------
array_sort([1, 4, 3, 2], 'desc'): [4,3,2,1]
```
This example demonstrates how NULL values are handled in descending order, with NULLs appearing before all non-NULL values:
```sql
SELECT ARRAY_SORT([1, 4, 3, 2, NULL], 'DESC');
-[ RECORD 1 ]-----------------------------------
array_sort([1, 4, 3, 2, null], 'desc'): [NULL,4,3,2,1] …
```
> docs: ARRAY_SORT updates

- docs/en/sql-reference/00-sql-reference/10-data-types/20-data-type-time-date-types.md
Databend automatically converts invalid Date or Timestamp values to their minimum valid equivalents, `1000-01-01` for dates and `1000-01-01 00:00:00` for timestamps, ensuring consistency when working with out-of-range or incorrectly formatted dates and timestamps. 
Examples:
```sql
-- Attempts to add one day to the maximum date, exceeding the valid range.
-- Result: Returns DateMIN (1000-01-01) instead of an error.
SELECT ADD_DAYS(TO_DATE('9999-12-31'), 1);
┌────────────────────────────────────┐
│ add_days(to_date('9999-12-31'), 1) │
├────────────────────────────────────┤
│ 1000-01-01                         │
└────────────────────────────────────┘
```
```sql
-- Attempts to subtract one minute from the minimum date, which would be invalid.
-- Result: Returns DateMIN (1000-01-01 00:00:00), …
```
> docs: handling invalid datetime values

- docs/en/sql-reference/10-sql-commands/20-query-syntax/with-stream-hints.md
Updated description of MAX_BATCH_SIZE:
> For streams with a large backlog of changes, such as when a stream hasn’t been consumed for a long time, setting MAX_BATCH_SIZE or using a smaller value is not recommended, as it may reduce capture efficiency.
> docs: With stream hints updates

- docs/en/sql-reference/20-sql-functions/05-datetime-functions/to-timestamp.md
added new syntax:` TO_TIMESTAMP(<int>, <scale>)`
> docs: TO_TIMESTAMP(<int>, <scale>)

- i18n/en/code.json
- i18n/zh/code.json
- src/components/DocsOverview/index.tsx
This fixes a typo in the docs ("Cummunity" -> "Community").
> Fix Community Typo

- docs/en/sql-reference/00-sql-reference/20-system-tables/system-temp-files.md
- docs/en/sql-reference/10-sql-commands/50-administration-cmds/09-vacuum-temp-files.md
- Removed the `RETAIN` parameter. 
- Updated the examples.
> docs: VACUUM TEMPORARY FILES updates

- docs/cn/guides/10-deploy/01-deploy/02-production/02-deploying-databend-on-kubernetes.md
- docs/en/guides/10-deploy/01-deploy/02-production/02-deploying-databend-on-kubernetes.md
I added namespace "databend-meta" based on the above contents because there was an error that prevented access to the meta node when I access query node without accidentally specifying the namespace databend-meta.
"ERROR databend_common_meta_client::established_client: established_client.rs:73 fail to update leader: "node(databend-meta-2.databend-meta.databend-meta.svc.cluster.local:9191) to set is not in the nodes list"; endpoints: current:Some("databend-meta-0.databend-meta.databend-meta.svc:9191"), all:[databend-meta-0.databend-meta.databend-meta.svc:9191, databend-meta-1.databend-meta.databend-meta.svc:9191, databend-meta-2.databend-meta.databend-meta.svc:9191]"
> fix deploying databend on k8s add namespace databend-meta

- docs/en/guides/55-performance/01-virtual-column.md
Fixes: https://github.com/databendlabs/databend/issues/17303
> docs: update virtual cols example

- docs/en/guides/40-load-data/05-continuous-data-pipelines/01-stream.md
`append-only` defaults to `true`.
> docs: fix stream

- docs/en/sql-reference/20-sql-functions/05-datetime-functions/extract.md
```sql
EXTRACT( YEAR | QUARTER | MONTH | WEEK | DAY | HOUR | MINUTE | SECOND | DOW | DOY | EPOCH FROM <date_or_time_expr> )
```
- `EPOCH`: The number of seconds since 1970-01-01 00:00:00.
> docs: extract supports EPOCH

- docs/en/sql-reference/10-sql-commands/20-query-syntax/01-query-select.md
Databend extends SQL syntax by allowing queries to start with `FROM <table>` without explicitly using `SELECT *`:
```sql
FROM my_table;
```
This is equivalent to:
```sql
SELECT * FROM my_table;
```
> docs: Retrieving All Columns with "FROM <tbl>"

- docs/en/sql-reference/10-sql-commands/00-ddl/18-procedure/desc-procedure.md
```sql
DESC | DESCRIBE PROCEDURE <procedure_name>([<parameter_type1>, <parameter_type2>, ...])
```
> docs: desc procedure

- docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-stddev-samp.md
added note: STDDEV_SAMP() returns NULL instead of 0 when there is only one input record.
> docs: STDDEV_SAMP udpates

- docs/en/sql-reference/10-sql-commands/00-ddl/01-table/92-attach-table.md
- docs/en/tutorials/databend-cloud/link-tables.md
Added the ability to specify selected cols when attaching a table:
- Updated ATTACH TABLE syntax:
```sql
ATTACH TABLE <target_table_name> [ ( <column_list> ) ] '<source_table_data_URI>'
CONNECTION = ( <connection_parameters> )
```
- Updated ATTACH TABLE examples.
- Added a new tutorial: Linking Tables with ATTACH TABLE
> docs: Attach tbl 

- docs/en/sql-reference/10-sql-commands/00-ddl/02-user/01-user-create-user.md
- docs/en/sql-reference/10-sql-commands/00-ddl/02-user/04-user-create-role.md
A SQL user or role name cannot contain the following illegal characters:
- Single quote (')
- Double quote (")
- Backspace (\b)
- Form feed (\f)
> docs: illegal characters for user o role name 

- docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md
Log level for [log.file] & [log.stderr] now follows [env_logger](https://docs.rs/env_logger/latest/env_logger/) syntax: `error`, `warn`, `info`, `debug`, `trace`, `off`. Defaults to `warn,databend_=info,openraft=info`.
> docs: log level updates

- docs/en/sql-reference/20-sql-functions/06-string-functions/left.md
Description updated: Returns the leftmost `len` characters from the string `str`, or NULL if any argument is NULL. If `len` is greater than the length of `str`, the entire `str` is returned.
Example updated:
```sql
SELECT LEFT('foobarbar', 5), LEFT('foobarbar', 10);
┌──────────────────────────────────────────────┐
│ left('foobarbar', 5) │ left('foobarbar', 10) │
├──────────────────────┼───────────────────────┤
│ fooba                │ foobarbar             │
└──────────────────────────────────────────────┘
```
> docs: LEFT updates

- docs/en/sql-reference/00-sql-reference/50-file-format-options.md
- added copy into options for ORC (same as parquet): `ERROR` & `FIELD_DEFAULT`.
- removed `TYPE_DEFAULT` for NDJSON.
> docs: orc copy into options

- docs/en/guides/51-access-data-lake/02-iceberg.md
- docs/en/sql-reference/20-sql-functions/17-table-functions/iceberg-manifest.md
- docs/en/sql-reference/20-sql-functions/17-table-functions/iceberg-snapshot.md
Added tbl functions:
- ICEBERG_MANIFEST
- ICEBERG_SNAPSHOT
> docs: iceberg tbl functions

- docs/en/sql-reference/00-sql-reference/50-file-format-options.md
- added `COMPRESSION` options for Parquet: `zstd` (default) & `snappy`.
- marked all file format options with `Load Only` if the option is for data loading only, or `Unload Only` for data unloading only.
> docs: parquet compression options

- docs/en/sql-reference/20-sql-functions/06-string-functions/glob.md
- docs/en/sql-reference/20-sql-functions/06-string-functions/index.md
> docs: glob function

- docs/en/sql-reference/20-sql-functions/15-context-functions/last-query-id.md
This PR updated LAST_QUERY_ID with detailed explanations and examples. 
Just refactored the document for LAST_QUERY_ID based on my own test results. Key updates includes that the functions accepts both positives & negatives, and how the queries in a session are indexed in either way:
|                                              | Positive | Negative |
|----------------------------------------------|----------|----------|
| `SELECT 1`                                   | 1        | -4       |
| `SELECT 2`                                   | 2        | -3       |
| `SELECT 3`                                   | 3        | -2       |
| `SELECT LAST_QUERY_ID(-2), LAST_QUERY_ID(3)` | 4        | -1       |
> docs: LAST_QUERY_ID

- docs/en/guides/40-load-data/03-load-semistructured/00-load-parquet.md
- docs/en/guides/40-load-data/03-load-semistructured/01-load-csv.md
- docs/en/guides/40-load-data/03-load-semistructured/02-load-tsv.md
- docs/en/guides/40-load-data/03-load-semistructured/03-load-ndjson.md
- docs/en/guides/40-load-data/03-load-semistructured/04-load-orc.md
- docs/en/guides/40-load-data/03-load-semistructured/05-load-avro.md
- docs/en/guides/40-load-data/03-load-semistructured/index.md
- docs/en/sql-reference/00-sql-reference/50-file-format-options.md
- docs/en/sql-reference/10-sql-commands/10-dml/dml-copy-into-table.md
- Introduced Avro as a new format Databend supports for.
- Added `MISSING_FIELD_AS` as the file option. 
- Added a short tutorial: Loading Avro Data into Databend from Remote HTTP URL
> docs: avro file format

- docs/en/sql-reference/20-sql-functions/05-datetime-functions/date-diff.md
- docs/en/sql-reference/20-sql-functions/05-datetime-functions/date-part.md
- docs/en/sql-reference/20-sql-functions/05-datetime-functions/extract.md
- docs/en/sql-reference/20-sql-functions/05-datetime-functions/index.md
- docs/en/sql-reference/20-sql-functions/05-datetime-functions/millennium.md
- docs/en/sql-reference/20-sql-functions/05-datetime-functions/yearweek.md
This PR depends on https://github.com/databendlabs/databend/pull/17759:
- DATE_PART, EXTRACT, and DATE_DIFF added support for new keywords: `ISODOW` | `YEARWEEK` | `MILLENNIUM`. 
- Added functions: MILLENNIUM and YEARWEEK.
> docs: support for ISODOW | YEARWEEK | MILLENNIUM

- docs/en/guides/10-deploy/03-monitor/tools/jaeger.md
databend-query version: v1.2.731-nightly
Databend Query start failure, cause: anyhow. Code: 1002, Text = TOML parse error at line 105, column 6
|
105 | on = "true"
|      ^^^^^^
invalid type: string "true", expected a boolean
, source: None
TOML parse error at line 105, column 6
|
105 | on = "true"
|      ^^^^^^
invalid type: string "true", expected a boolean
> Fix: Update jaeger.md

- docs/en/sql-reference/10-sql-commands/00-ddl/04-task/01-ddl-create_task.md
- docs/en/sql-reference/10-sql-commands/10-dml/dml-insert-multi.md
- docs/en/sql-reference/10-sql-commands/10-dml/dml-insert.md
- docs/en/sql-reference/20-sql-functions/03-conditional-functions/greatest-ignore-nulls.md
- docs/en/sql-reference/20-sql-functions/03-conditional-functions/greatest.md
- docs/en/sql-reference/20-sql-functions/03-conditional-functions/if.md
- docs/en/sql-reference/20-sql-functions/03-conditional-functions/iff.md
- docs/en/sql-reference/20-sql-functions/03-conditional-functions/least-ignore-nulls.md
- docs/en/sql-reference/20-sql-functions/03-conditional-functions/least.md
- docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-covar-pop.md
- docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-covar-samp.md
- docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-var-pop.md
- docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-var-samp.md
- docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-variance-pop.md
- docs/en/sql-reference/20-sql-functions/07-aggregate-functions/aggregate-variance-samp.md
This change is related to https://github.com/databendlabs/databend/pull/17920:
- Support CREATE OR REPLACE syntax for tasks
- IFF is now an alias for the IF function
- GREATEST and LEAST will now return NULL if any input argument is NULL
- Added GREATEST_IGNORE_NULLS and LEAST_IGNORE_NULLS, which ignore NULL values (same behavior as the previous GREATEST and LEAST)
- Added VAR_POP and VARIANCE_POP as aliases for the COVAR_POP function
- Added VAR_SAMP and VARIANCE_SAMP as aliases for the COVAR_SAMP function
- Support INSERT OVERWRITE INTO syntax (equivalent to INSERT OVERWRITE)
> docs: function alias

- docs/en/guides/56-security/audit-trail.md
- docs/en/guides/56-security/index.md
- docs/en/sql-reference/00-sql-reference/32-system-history-tables/access-history.md
- docs/en/sql-reference/00-sql-reference/32-system-history-tables/index.md
- docs/en/sql-reference/00-sql-reference/32-system-history-tables/log-history.md
- docs/en/sql-reference/00-sql-reference/32-system-history-tables/login-history.md
- docs/en/sql-reference/00-sql-reference/32-system-history-tables/profile-history.md
- docs/en/sql-reference/00-sql-reference/32-system-history-tables/query-history.md
- Add new "Audit Trail" guide for database activity auditing.
- Security index: add "Audit Trail" entry.
- Rewrite and standardize all system_history table docs:
- Add EEFeature badges and concise feature summaries.
- Clarify table purposes and use cases.
- System History Tables index:
- New use-case-focused table overview.
- Clearer Cloud vs. Self-Hosted setup, add S3 storage example.
> aduit trail and system history tables

- docs/en/guides/51-ai-functions/02-built-in-functions.md
- docs/en/sql-reference/00-sql-reference/10-data-types/index.md
- docs/en/sql-reference/00-sql-reference/10-data-types/vector.md
- docs/en/sql-reference/20-sql-functions/11-ai-functions/02-ai-embedding-vector.md
- docs/en/sql-reference/20-sql-functions/11-vector-distance-functions/00-vector-cosine-distance.md
- docs/en/sql-reference/20-sql-functions/11-vector-distance-functions/01-vector-l2-distance.md
- docs/en/sql-reference/20-sql-functions/11-vector-distance-functions/02-vector-l1-distance.md
- docs/en/sql-reference/20-sql-functions/11-vector-distance-functions/index.md
> vector data type

- docs/en/guides/56-security/access-control/01-privileges.md
- docs/en/sql-reference/10-sql-commands/00-ddl/05-view/ddl-create-view.md
- docs/en/sql-reference/10-sql-commands/00-ddl/13-connection/create-connection.md
wait https://github.com/databendlabs/databend/pull/18382 release
> chore: add privilege doc about view and connection

- docs/en/sql-reference/20-sql-functions/08-window-functions/cume-dist.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/dense-rank.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/first-value.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/index.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/lag.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/last-value.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/lead.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/nth-value.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/ntile.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/percent_rank.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/rank.md
- docs/en/sql-reference/20-sql-functions/08-window-functions/row-number.md
> refine the window functions

- docs/en/guides/40-load-data/04-transform/03-querying-ndjson.md
- Add comprehensive introduction explaining what NDJSON is and its advantages
- Provide concrete NDJSON data examples showing realistic book catalog data
- Add detailed explanations for all existing code examples including syntax breakdown
- Explain metadata columns usage and practical use cases
- Add related documentation links for better navigation
- Enhance tutorial flow with clear step-by-step context
---
> improve NDJSON querying documentation with context and explanations

- docs/en/guides/54-query/03-udf.md
- docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-alter-function.md
- docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-create-function-embedded.md
- docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-create-function.md
- docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-create-table-function.md
- docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-drop-function.md
- docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/ddl-show-user-functions.md
- docs/en/sql-reference/10-sql-commands/00-ddl/10-udf/index.md
- add UDTF
- improve the org of udf
https://github.com/databendlabs/databend/pull/18575
https://github.com/databendlabs/databend/pull/18511
> udf: add UDTF and improve the org of UDF

- docs/en/guides/10-deploy/04-references/02-node-config/02-query-config.md
Updates spill configuration documentation to reflect the new unified format introduced in PR databendlabs/databend#18593.
- Add unified `[spill.storage]` configuration format for fs and s3 storage types
- Detailed parameter descriptions including max_bytes fallback behavior to main storage
- Legacy format collapsed with version compatibility note (< v1.2.901)
- Updated version requirement to v1.2.901
> feat(docs): update spill configuration with unified format
